### ISSUE TITLE
[BUG] additionalProperties sometimes breaks

### ISSUE THREAD

**Issue by spacether** [openapi-json-schema-tools/openapi-json-schema-generator#92]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When using an SchemaObject, that contains the `additionalProperties` attribute with `type: object`, I get the error: 
`AttributeError: type object 'MetaOapg' has no attribute 'additional_properties'`.

As I have tested this, I have come to the conclusion that this only occurs, when there are other Schemas with `additionalProperties` defined.

##### openapi-generator version

Version 6.3.0 Python

##### OpenAPI declaration file content or url

This my minimal Example to reproduce the bug
```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: issue 13997 spec
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers: []
tags: []
paths: {}
components:
  schemas:
    Event:
      type: object
      required:
        - apiVersion
        - modules
      properties:
        apiVersion:
          type: string
        timeout:
          type: integer
          format: int32
          example: 10000
        modules:
          type: object
          additionalProperties:
            type: object
    UploadEvent:
      type: object
      properties:
        uploadId:
          type: string
          example: "6Ms5S3"
        result:
          type: object
          additionalProperties:
            type: array
            items:
              type: object
```
**And for some reason this works (without the second event):**
```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: issue 13997 spec
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers: []
tags: []
paths: {}
components:
  schemas:
    Event:
      type: object
      required:
        - apiVersion
        - modules
      properties:
        apiVersion:
          type: string
        timeout:
          type: integer
          format: int32
          example: 10000
        modules:
          type: object
          additionalProperties:
            type: object
```
##### Generation Details

`java -jar openapi-generator-cli-6.3.0.jar generate -i additional.yaml -g python`

##### Steps to reproduce

Generate with specified yaml file above and try to import Event like: `from openapi_client.model.event import Event`

##### Complete Stacktrace
```
Traceback (most recent call last):
  File "sample.py", line 2, in <module>
    from devaice_web_api_client.model.event import Event
  File "/home/user/.local/lib/python3.8/site-packages/openapi_client/model/event.py", line 26, in <module>
    class Event(
  File "/home/user/.local/lib/python3.8/site-packages/openapi_client/model/event.py", line 36, in Event
    class MetaOapg:
  File "/home/user/.local/lib/python3.8/site-packages/openapi_client/model/event.py", line 42, in MetaOapg
    class properties:
  File "/home/user/.local/lib/python3.8/site-packages/openapi_client/model/event.py", line 46, in properties
    class modules(
  File "/home/user/.local/lib/python3.8/site-packages/openapi_client/model/event.py", line 65, in modules
    **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, ],
AttributeError: type object 'MetaOapg' has no attribute 'additional_properties'
```
Synonym issue from https://github.com/OpenAPITools/openapi-generator/issues/14078
Thank you @Poolmann

**Comment by spacether** [comment]
With both components, the generated event class is shown below.
Per generated code:
- Event.MetaOapg.properties.modules contain items instead of the defined additional_properties

Research is needed in the Java layer there

```
class Event(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "apiVersion",
            "modules",
        }
        
        class properties:
            apiVersion = schemas.StrSchema
            
            
            class modules(
                schemas.DictSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.DictSchema
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.items:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.items:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, dict, frozendict.frozendict, ],
                ) -> 'modules':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            timeout = schemas.Int32Schema
            __annotations__ = {
                "apiVersion": apiVersion,
                "modules": modules,
                "timeout": timeout,
            }
    
    apiVersion: MetaOapg.properties.apiVersion
    modules: MetaOapg.properties.modules
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["apiVersion"]) -> MetaOapg.properties.apiVersion: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["modules"]) -> MetaOapg.properties.modules: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timeout"]) -> MetaOapg.properties.timeout: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["apiVersion", "modules", "timeout", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["apiVersion"]) -> MetaOapg.properties.apiVersion: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["modules"]) -> MetaOapg.properties.modules: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timeout"]) -> typing.Union[MetaOapg.properties.timeout, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["apiVersion", "modules", "timeout", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        apiVersion: typing.Union[MetaOapg.properties.apiVersion, str, ],
        modules: typing.Union[MetaOapg.properties.modules, dict, frozendict.frozendict, ],
        timeout: typing.Union[MetaOapg.properties.timeout, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Event':
        return super().__new__(
            cls,
            *_args,
            apiVersion=apiVersion,
            modules=modules,
            timeout=timeout,
            _configuration=_configuration,
            **kwargs,
        )
```

**Comment by spacether** [comment]
`Event.MetaOapg.properties.modules.addtional_properties.basename` is items when it should be additional_properties

**Comment by spacether** [comment]
The swap happens after processing the second model, when exactly does it change?

**Comment by spacether** [comment]
This happens because the items schema and the additionalProperties schema have the same schema, and the code uses the same baseName of "". The solution is to use a default baseName that is different for items and additional_properties. `getItemsName`, `getAdditionalPropertiesName` that all generators implement.
A java test of it would be to call fromProperty on two sequential schemas, both of which include the same subschema under additionalProperties and items
```
arrayProperty:
  type: array
  items:
    type:
      object
objProperty:
  type: object
  additionalProperties:
    type:
      object
```
